# Generated by Django 5.1.6 on 2025-03-05 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="vendor",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.DeleteModel(
            name="PurchaseOrder",
        ),
    ]
