# Generated by Django 5.1.6 on 2025-03-08 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0002_remove_purchaseorder_vendor_delete_invoice_and_more"),
        ("finance_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalinventoryitem",
            name="part",
        ),
        migrations.RemoveField(
            model_name="historicalinventoryitem",
            name="price_per_unit",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="part",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="price_per_unit",
        ),
        migrations.AddField(
            model_name="historicalinventoryitem",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="book_app.vendor",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="book_app.vendor",
            ),
        ),
    ]
