# Generated by Django 5.1.6 on 2025-03-08 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0002_remove_purchaseorder_vendor_delete_invoice_and_more"),
        ("finance_app", "0002_remove_historicalinventoryitem_part_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="book_app.vendor"
            ),
        ),
    ]
