# Generated by Django 5.1.6 on 2025-03-08 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0004_inventorycount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpurchaseorder",
            name="total_amount",
        ),
        migrations.RemoveField(
            model_name="historicalpurchaseorder",
            name="vendor",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="total_amount",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="vendor",
        ),
        migrations.AddField(
            model_name="historicalpurchaseorder",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="finance_app.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="historicalpurchaseorder",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance_app.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="PurchaseOrderItem",
        ),
    ]
