# Generated by Django 5.1.6 on 2025-03-08 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0005_remove_historicalpurchaseorder_total_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="inventory_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="finance_app.inventoryitem",
            ),
        ),
    ]
